<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R使い方入門：操作変数法</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="03iv_files/libs/clipboard/clipboard.min.js"></script>
<script src="03iv_files/libs/quarto-html/quarto.js"></script>
<script src="03iv_files/libs/quarto-html/popper.min.js"></script>
<script src="03iv_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="03iv_files/libs/quarto-html/anchor.min.js"></script>
<link href="03iv_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="03iv_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="03iv_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="03iv_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="03iv_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#操作変数法instrumental-variables-method" id="toc-操作変数法instrumental-variables-method" class="nav-link active" data-scroll-target="#操作変数法instrumental-variables-method"><span class="header-section-number">1</span> 操作変数法（Instrumental Variables Method）</a></li>
  <li><a href="#複数の操作変数過剰識別" id="toc-複数の操作変数過剰識別" class="nav-link" data-scroll-target="#複数の操作変数過剰識別"><span class="header-section-number">2</span> 複数の操作変数（過剰識別）</a></li>
  <li><a href="#ivregの拡張機能" id="toc-ivregの拡張機能" class="nav-link" data-scroll-target="#ivregの拡張機能"><span class="header-section-number">3</span> ivregの拡張機能</a></li>
  <li><a href="#estimatrパッケージ" id="toc-estimatrパッケージ" class="nav-link" data-scroll-target="#estimatrパッケージ"><span class="header-section-number">4</span> estimatrパッケージ</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="03iv.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="03iv.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R使い方入門：操作変数法</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="操作変数法instrumental-variables-method" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="操作変数法instrumental-variables-method"><span class="header-section-number">1</span> 操作変数法（Instrumental Variables Method）</h2>
<p>回帰分析において、説明変数と誤差項が相関している場合（内生性がある場合）、通常の最小二乗法（OLS）による推定量はバイアスを持ち、一致性を失います。教育年数が賃金に与える影響を推定するミンサー方程式の例では、個人の「能力」などの観察できない要因が、教育年数と賃金の両方に影響を与える可能性があります。この場合、教育年数の係数は過大評価（上方バイアス）される傾向があります。</p>
<p>このような内生性の問題に対処するために用いられるのが<strong>操作変数法（IV法）</strong>です。</p>
<section id="データの読み込み" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="データの読み込み"><span class="header-section-number">1.1</span> データの読み込み</h3>
<p>まず、データを読み込みます。ここでは <code>8_income.csv</code> を使用します。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>income8 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"8_income.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(income8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  exper exper2 mbirth moyeduc payeduc sibs yeduc  lincome
1    19    361      6       9       9    1     9 5.703783
2    19    361      4      12      12    1     9 5.991465
3    19    361      1       9       9    1     9 6.214608
4    19    361      9       9       9    1     9 6.214608
5    23    529      8       9       9    3     9 6.309918
6    23    529     11      12      13    2     9 6.309918</code></pre>
</div>
</div>
</section>
<section id="olsによる推定ベースライン" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="olsによる推定ベースライン"><span class="header-section-number">1.2</span> OLSによる推定（ベースライン）</h3>
<p>比較のために、まずは通常の最小二乗法（OLS）でミンサー方程式を推定します。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lincome <span class="sc">~</span> yeduc <span class="sc">+</span> exper <span class="sc">+</span> exper2, <span class="at">data =</span> income8)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lincome ~ yeduc + exper + exper2, data = income8)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.36671 -0.15058 -0.00815  0.15856  1.25601 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.3197739  0.1387946  31.124  &lt; 2e-16 ***
yeduc        0.0842350  0.0062404  13.498  &lt; 2e-16 ***
exper        0.0576637  0.0152888   3.772 0.000175 ***
exper2      -0.0008313  0.0005259  -1.581 0.114371    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3092 on 730 degrees of freedom
Multiple R-squared:  0.2487,    Adjusted R-squared:  0.2456 
F-statistic: 80.53 on 3 and 730 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><code>summary(reg1)</code> の結果を確認すると、教育年数 <code>yeduc</code> の係数は正で有意であることがわかります。しかし、前述の通り、この推定値には内生性によるバイアスが含まれている可能性があります。</p>
</section>
<section id="操作変数法による推定" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="操作変数法による推定"><span class="header-section-number">1.3</span> 操作変数法による推定</h3>
<p>次に、操作変数法を用いて推定を行います。 ここでは、本人の教育年数 <code>yeduc</code> の操作変数として、親の教育年数（あるいは学費の支払い能力などに関連する変数と想定される）<code>payeduc</code> を使用します。</p>
<p>操作変数が満たすべき条件は以下の2つです：</p>
<ol type="1">
<li><strong>関連性（Relevance）</strong>: 操作変数（<code>payeduc</code>）は内生変数（<code>yeduc</code>）と相関していること。</li>
<li><strong>外生性（Exogeneity）</strong>: 操作変数（<code>payeduc</code>）は誤差項とは相関していないこと（賃金に対して、教育年数を通じた経路以外で直接的な影響を持たないこと）。</li>
</ol>
<p>Rで操作変数法を行うには、<code>AER</code> パッケージの <code>ivreg()</code> 関数が便利です。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 操作変数法による推定</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 式の書き方: 従属変数 ~ 内生変数 + 外生変数 | 操作変数 + 外生変数</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ivreg1 <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(lincome <span class="sc">~</span> yeduc <span class="sc">+</span> exper <span class="sc">+</span> exper2 <span class="sc">|</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    exper <span class="sc">+</span> exper2 <span class="sc">+</span> payeduc, <span class="at">data =</span> income8)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = lincome ~ yeduc + exper + exper2 | exper + exper2 + 
    payeduc, data = income8)

Residuals:
      Min        1Q    Median        3Q       Max 
-1.350328 -0.146688 -0.009026  0.162186  1.236270 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.4485971  0.3489064  12.750  &lt; 2e-16 ***
yeduc        0.0752049  0.0232869   3.230 0.001296 ** 
exper        0.0597410  0.0161570   3.698 0.000234 ***
exper2      -0.0009639  0.0006213  -1.552 0.121191    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3097 on 730 degrees of freedom
Multiple R-Squared: 0.2465, Adjusted R-squared: 0.2434 
Wald test: 23.22 on 3 and 730 DF,  p-value: 2.31e-14 </code></pre>
</div>
</div>
<p><code>ivreg()</code> の式の <code>|</code> の右側には、<strong>モデルに含まれるすべての外生変数</strong>（ここでは <code>exper</code>, <code>exper2</code>）と、<strong>操作変数</strong>（<code>payeduc</code>）を記述します。内生変数である <code>yeduc</code> は右側には含めません。</p>
</section>
<section id="結果の解釈" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="結果の解釈"><span class="header-section-number">1.4</span> 結果の解釈</h3>
<p>OLSの結果（<code>reg1</code>）とIV法の結果（<code>ivreg1</code>）を比較してみましょう。</p>
<ul>
<li><strong>OLS推定値（<code>yeduc</code>）</strong>: 約 0.084</li>
<li><strong>IV推定値（<code>yeduc</code>）</strong>: 約 0.075</li>
</ul>
<p>OLSによる教育年数の収益率（約8.4%）と比較して、操作変数法による推定値（約7.5%）は小さくなりました。 これは、OLS推定値が「能力」などの観察されない要因によって上方バイアスを持っていた（過大評価されていた）という仮説と整合的です。能力が高い人は教育年数が長く、かつ賃金も高い傾向があるため、能力をコントロールできないOLSでは教育の効果が実際よりも大きく推定されてしまう傾向があります。操作変数法を用いることで、このバイアスを取り除き、より純粋な教育の効果に近づくことができました。</p>
<p>ただし、IV推定値も依然として統計的に有意であり、教育が賃金に正の効果を与えるという結論自体は変わりません。</p>
</section>
</section>
<section id="複数の操作変数過剰識別" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="複数の操作変数過剰識別"><span class="header-section-number">2</span> 複数の操作変数（過剰識別）</h2>
<p>次に、操作変数を追加して分析を行います。ここでは、<code>payeduc</code>（親の教育費支払い能力）に加えて、<code>sibs</code>（兄弟姉妹数）も操作変数として使用します。兄弟姉妹数が多いと、一人当たりの教育資源が減少し、教育年数に影響を与える可能性がありますが、本人の賃金には直接影響しない（外生性がある）と仮定します。</p>
<section id="ivregによる推定" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="ivregによる推定"><span class="header-section-number">2.1</span> ivregによる推定</h3>
<p><code>ivreg()</code>関数の <code>|</code> の右側に <code>sibs</code> を追加します。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 兄弟姉妹数（sibs）も操作変数として追加</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>ivreg2 <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(lincome <span class="sc">~</span> yeduc <span class="sc">+</span> exper <span class="sc">+</span> exper2 <span class="sc">|</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    exper <span class="sc">+</span> exper2 <span class="sc">+</span> payeduc <span class="sc">+</span> sibs, <span class="at">data =</span> income8)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = lincome ~ yeduc + exper + exper2 | exper + exper2 + 
    payeduc + sibs, data = income8)

Residuals:
      Min        1Q    Median        3Q       Max 
-1.340720 -0.153748 -0.009586  0.163970  1.224695 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.5241448  0.3286803  13.765  &lt; 2e-16 ***
yeduc        0.0699093  0.0217875   3.209 0.001392 ** 
exper        0.0609592  0.0160773   3.792 0.000162 ***
exper2      -0.0010417  0.0006104  -1.707 0.088290 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3103 on 730 degrees of freedom
Multiple R-Squared: 0.2432, Adjusted R-squared: 0.2401 
Wald test: 23.09 on 3 and 730 DF,  p-value: 2.753e-14 </code></pre>
</div>
</div>
</section>
<section id="段階最小二乗法2slsの手動計算" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="段階最小二乗法2slsの手動計算"><span class="header-section-number">2.2</span> 2段階最小二乗法（2SLS）の手動計算</h3>
<p>操作変数法は「2段階最小二乗法（2SLS）」とも呼ばれます。この仕組みを理解するために、<code>lm()</code>関数を使って手動で計算してみましょう。</p>
<ol type="1">
<li><strong>第1段階</strong>: 内生変数（<code>yeduc</code>）を、すべての外生変数（<code>exper</code>, <code>exper2</code>, <code>payeduc</code>, <code>sibs</code>）に回帰させ、予測値（<code>fitted values</code>）を求めます。</li>
<li><strong>第2段階</strong>: 本来の回帰式の内生変数（<code>yeduc</code>）を、第1段階で求めた予測値に置き換えて回帰を行います。</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 第1段階：内生変数（yeduc）をすべての外生変数に回帰</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ols1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(yeduc <span class="sc">~</span> exper <span class="sc">+</span> exper2 <span class="sc">+</span> payeduc <span class="sc">+</span> sibs, <span class="at">data =</span> income8)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 第2段階：yeducの予測値（fitted(ols1)）を使って本回帰</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ols2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lincome <span class="sc">~</span> <span class="fu">fitted</span>(ols1) <span class="sc">+</span> exper <span class="sc">+</span> exper2, <span class="at">data =</span> income8)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lincome ~ fitted(ols1) + exper + exper2, data = income8)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.1985 -0.2114  0.0001  0.1888  1.1450 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   4.524145   0.364011  12.429  &lt; 2e-16 ***
fitted(ols1)  0.069909   0.024130   2.897 0.003877 ** 
exper         0.060959   0.017805   3.424 0.000652 ***
exper2       -0.001042   0.000676  -1.541 0.123722    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3437 on 730 degrees of freedom
Multiple R-squared:  0.0718,    Adjusted R-squared:  0.06799 
F-statistic: 18.82 on 3 and 730 DF,  p-value: 9.08e-12</code></pre>
</div>
</div>
<p>手動計算による <code>fitted(ols1)</code> の係数は、<code>ivreg2</code> の <code>yeduc</code> の係数と一致することを確認してください。これにより、操作変数法が <strong>内生変数のうち、外生変数によって説明できる部分（予測値）</strong> のみを使って回帰を行っていることがわかります。ただし、標準誤差は異なっているために検定に使えません。</p>
</section>
<section id="結果の解釈-1" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="結果の解釈-1"><span class="header-section-number">2.3</span> 結果の解釈</h3>
<p>複数の操作変数を用いた結果（<code>ivreg2</code>）を確認しましょう。</p>
<ul>
<li><strong>IV推定値（<code>yeduc</code>）</strong>: 約 0.070</li>
</ul>
<p>単一の操作変数を用いた場合（約0.075）と比較して、推定値はさらに少し小さくなりましたが、大きな違いはありません。また、統計的有意性も維持されています（p値 &lt; 0.01）。 複数の操作変数を用いることで、推定の効率性が向上する可能性がありますが、同時に過剰識別検定（Sargan検定など）を行うことで操作変数の妥当性をチェックすることも可能になります（ここでは省略）。 兄弟姉妹数を操作変数に追加しても、教育の収益率が約7%程度であるという結論は頑健であることが示唆されます。</p>
</section>
</section>
<section id="ivregの拡張機能" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="ivregの拡張機能"><span class="header-section-number">3</span> ivregの拡張機能</h2>
<p><code>ivreg</code>関数には、多くの拡張機能があります。</p>
<section id="診断統計量" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="診断統計量"><span class="header-section-number">3.1</span> 診断統計量</h3>
<p><code>summary()</code> 関数に <code>diagnostics = TRUE</code> オプションを指定することで、操作変数の妥当性を評価するための診断統計量を確認できます。これには、<strong>弱操作変数検定</strong> （Weak Instrument Test）や、<strong>Wu-Hausman</strong>（ハウスマン検定）や、<strong>過剰識別検定</strong> （Sargan Test）などが含まれます。弱操作変数検定は、操作変数が内生変数と十分に相関しているか（関連性条件）を評価し、過剰識別検定は、複数の操作変数がある場合に、それらがすべて外生性条件を満たしているか（誤差項と相関がないか）を評価します。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg2, <span class="at">diagnostics =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = lincome ~ yeduc + exper + exper2 | exper + exper2 + 
    payeduc + sibs, data = income8)

Residuals:
      Min        1Q    Median        3Q       Max 
-1.340720 -0.153748 -0.009586  0.163970  1.224695 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.5241448  0.3286803  13.765  &lt; 2e-16 ***
yeduc        0.0699093  0.0217875   3.209 0.001392 ** 
exper        0.0609592  0.0160773   3.792 0.000162 ***
exper2      -0.0010417  0.0006104  -1.707 0.088290 .  

Diagnostic tests:
                 df1 df2 statistic  p-value    
Weak instruments   2 729    32.831 2.23e-14 ***
Wu-Hausman         1 729     0.474    0.491    
Sargan             1  NA     0.403    0.525    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3103 on 730 degrees of freedom
Multiple R-Squared: 0.2432, Adjusted R-squared: 0.2401 
Wald test: 23.09 on 3 and 730 DF,  p-value: 2.753e-14 </code></pre>
</div>
</div>
<p>診断結果の解釈は以下の通りです。</p>
<ul>
<li><strong>Weak instruments（弱操作変数検定）</strong>: p値が非常に小さく（&lt; 0.01）、帰無仮説（操作変数が弱い）は棄却されます。したがって、操作変数は内生変数と十分に強い相関を持っていると言えます。</li>
<li><strong>Wu-Hausman（ハウスマン検定）</strong>: p値は約0.491であり、帰無仮説（OLSとIVの推定値に差がない＝内生性がない）を棄却できません。これは、統計的にはOLS推定値とIV推定値に有意な差が見られないことを示唆しています（ただし、理論的に内生性が疑われる場合はIV法を用いることが推奨されることもあります）。</li>
<li><strong>Sargan（過剰識別検定）</strong>: p値は約0.525であり、帰無仮説（すべての操作変数が外生である）を棄却できません。これは、使用した操作変数（<code>payeduc</code> と <code>sibs</code>）が外生性条件を満たしているという仮定と矛盾しないことを示しています。</li>
</ul>
<p>なお過剰識別検定は操作変数の数が内生変数の数より厳密に多くなければ計算されません。</p>
</section>
<section id="ロバスト標準誤差" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="ロバスト標準誤差"><span class="header-section-number">3.2</span> ロバスト標準誤差</h3>
<p>回帰分析において、誤差項の分散が均一でない <strong>不均一分散</strong> （heteroskedasticity）が存在する場合、通常の標準誤差は過小評価される傾向があり、統計的推論が誤る可能性があります。このような場合、<code>summary()</code> 関数に <code>vcov</code> オプションを指定し、<code>vcovHC()</code> 関数（<code>sandwich</code> パッケージ由来）を用いて <strong>ロバスト標準誤差</strong> （robust standard errors）を計算することで、不均一分散に頑健な標準誤差を得ることができます。<code>type = "HC1"</code> は、ロバスト標準誤差の計算方法の一つを指定しています。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg2, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(ivreg2, <span class="at">type =</span> <span class="st">"HC1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
ivreg(formula = lincome ~ yeduc + exper + exper2 | exper + exper2 + 
    payeduc + sibs, data = income8)

Residuals:
      Min        1Q    Median        3Q       Max 
-1.340720 -0.153748 -0.009586  0.163970  1.224695 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.5241448  0.3252807  13.908  &lt; 2e-16 ***
yeduc        0.0699093  0.0218722   3.196 0.001452 ** 
exper        0.0609592  0.0156393   3.898 0.000106 ***
exper2      -0.0010417  0.0005904  -1.764 0.078095 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3103 on 730 degrees of freedom
Multiple R-Squared: 0.2432, Adjusted R-squared: 0.2401 
Wald test: 25.21 on 3 and 730 DF,  p-value: 1.577e-15 </code></pre>
</div>
</div>
<p>ロバスト標準誤差を用いた場合でも、<code>yeduc</code> の係数は有意（p &lt; 0.01）であり、教育の効果が統計的に確からしいことが支持されます。通常の標準誤差と比較して、標準誤差の値がどのように変化しているかを確認することも重要です（ここでは大きな変化は見られません）。</p>
<p>なお、<code>diagnostics = TRUE</code> を同時に指定することで、診断統計量を含めて確認できますが、その場合、通常の標準誤差の結果となることに注意されたい。</p>
</section>
</section>
<section id="estimatrパッケージ" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="estimatrパッケージ"><span class="header-section-number">4</span> estimatrパッケージ</h2>
<p><code>estimatr</code>パッケージは、<code>ivreg</code>関数を用いて操作変数法を実行する際に、より簡単に診断統計量を確認することができます。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>ivreg3 <span class="ot">&lt;-</span> <span class="fu">iv_robust</span>(lincome <span class="sc">~</span> yeduc <span class="sc">+</span> exper <span class="sc">+</span> exper2 <span class="sc">|</span> exper <span class="sc">+</span> exper2 <span class="sc">+</span> payeduc <span class="sc">+</span> sibs, <span class="at">data =</span> income8, <span class="at">se_type =</span> <span class="st">"HC1"</span>, <span class="at">diagnostics =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
iv_robust(formula = lincome ~ yeduc + exper + exper2 | exper + 
    exper2 + payeduc + sibs, data = income8, se_type = "HC1", 
    diagnostics = TRUE)

Standard error type:  HC1 

Coefficients:
             Estimate Std. Error t value  Pr(&gt;|t|)  CI Lower  CI Upper  DF
(Intercept)  4.524145  0.3252807  13.908 3.510e-39  3.885548 5.1627420 730
yeduc        0.069909  0.0218722   3.196 1.452e-03  0.026969 0.1128492 730
exper        0.060959  0.0156393   3.898 1.060e-04  0.030256 0.0916626 730
exper2      -0.001042  0.0005904  -1.764 7.809e-02 -0.002201 0.0001174 730

Multiple R-squared:  0.2432 ,   Adjusted R-squared:  0.2401 
F-statistic: 25.21 on 3 and 730 DF,  p-value: 1.577e-15

Diagnostics:
                 numdf dendf  value  p.value    
Weak instruments     2   729 34.692 4.05e-15 ***
Wu-Hausman           1   729  0.487    0.485    
Overidentifying      1    NA  0.484    0.487    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><code>summary(ivreg3)</code> の結果を確認すると、<code>Standard error type: HC1</code> と表示されており、ロバスト標準誤差が使用されていることがわかります。 また、<code>yeduc</code> の係数（Estimate）は約 0.0699 であり、標準誤差（Std. Error）は約 0.0219 となっています。これは、先ほど <code>ivreg</code> と <code>vcovHC</code> を組み合わせて計算した結果と一致しています。</p>
<p>さらに、<code>Diagnostics</code> セクションには、弱操作変数検定（Weak instruments）、Wu-Hausman検定、過剰識別検定（Overidentifying）の結果も表示されています。これらも <code>ivreg</code> で <code>diagnostics = TRUE</code> を指定した際の結果と整合的ですが、ここではロバスト標準誤差を考慮した上で計算されている点に注意が必要です（ただし、この例では診断統計量の値も大きくは変わっていません）。</p>
<p><code>estimatr</code> パッケージを使うと、このように簡潔なコードでロバスト標準誤差と診断統計量を同時に得ることができるため、実務的にも非常に便利です。</p>
<p>なお、<code>se_type = "classical"</code> を指定することで、通常の標準誤差を計算することができます。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ivreg4 <span class="ot">&lt;-</span> <span class="fu">iv_robust</span>(lincome <span class="sc">~</span> yeduc <span class="sc">+</span> exper <span class="sc">+</span> exper2 <span class="sc">|</span> exper <span class="sc">+</span> exper2 <span class="sc">+</span> payeduc <span class="sc">+</span> sibs, <span class="at">data =</span> income8, <span class="at">se_type =</span> <span class="st">"classical"</span>, <span class="at">diagnostics =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ivreg4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
iv_robust(formula = lincome ~ yeduc + exper + exper2 | exper + 
    exper2 + payeduc + sibs, data = income8, se_type = "classical", 
    diagnostics = TRUE)

Standard error type:  classical 

Coefficients:
             Estimate Std. Error t value  Pr(&gt;|t|) CI Lower  CI Upper  DF
(Intercept)  4.524145  0.3286803  13.765 1.712e-38  3.87887 5.1694162 730
yeduc        0.069909  0.0217875   3.209 1.392e-03  0.02714 0.1126830 730
exper        0.060959  0.0160773   3.792 1.620e-04  0.02940 0.0925226 730
exper2      -0.001042  0.0006104  -1.707 8.829e-02 -0.00224 0.0001565 730

Multiple R-squared:  0.2432 ,   Adjusted R-squared:  0.2401 
F-statistic: 23.09 on 3 and 730 DF,  p-value: 2.753e-14

Diagnostics:
                 numdf dendf  value  p.value    
Weak instruments     2   729 32.831 2.23e-14 ***
Wu-Hausman           1   729  0.474    0.491    
Overidentifying      1    NA  0.403    0.525    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>